-- Macro backend prepare migration
-- Safe-by-default changes:
-- 1) Add backup table for rollback
-- 2) Add rollout columns on diet_records
-- 3) Add helper function to check whether macro fields are missing in item JSON

begin;

create table if not exists public.diet_records_backup (
  id bigint generated by default as identity primary key,
  backup_batch text not null,
  source_record jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.diet_records
  add column if not exists macros_rollout_version text,
  add column if not exists macros_updated_at timestamptz;

create or replace function public.item_missing_macros(item jsonb)
returns boolean
language sql
immutable
as $$
  select
    not (
      (item ? 'carb_g') and
      (item ? 'protein_g') and
      (item ? 'fat_g')
    );
$$;

comment on function public.item_missing_macros(jsonb)
is 'Returns true when any macro key (carb_g/protein_g/fat_g) is missing in item json.';

commit;

