-- Security hardening for diet backend
-- 1) Tighten RLS + grants for diet_records and diet_user_settings
-- 2) Add quota buckets + RPC for edge function rate limiting

begin;

-- ---------- Table privilege hardening ----------
revoke all on table public.diet_records from anon;
revoke all on table public.diet_records from public;
revoke all on table public.diet_user_settings from anon;
revoke all on table public.diet_user_settings from public;

grant select, insert, update, delete on table public.diet_records to authenticated;
grant select, insert, update on table public.diet_user_settings to authenticated;

-- ---------- RLS hardening: diet_records ----------
alter table public.diet_records enable row level security;

-- Clean legacy policy names if present.
drop policy if exists "select_own_records" on public.diet_records;
drop policy if exists "insert_own_records" on public.diet_records;
drop policy if exists "update_own_records" on public.diet_records;
drop policy if exists "delete_own_records" on public.diet_records;

drop policy if exists "diet_records_select_own" on public.diet_records;
drop policy if exists "diet_records_insert_own" on public.diet_records;
drop policy if exists "diet_records_update_own" on public.diet_records;
drop policy if exists "diet_records_delete_own" on public.diet_records;

create policy "diet_records_select_own"
on public.diet_records
for select
using (auth.uid() = user_id);

create policy "diet_records_insert_own"
on public.diet_records
for insert
with check (auth.uid() = user_id);

create policy "diet_records_update_own"
on public.diet_records
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "diet_records_delete_own"
on public.diet_records
for delete
using (auth.uid() = user_id);

-- ---------- RLS hardening: diet_user_settings ----------
alter table public.diet_user_settings enable row level security;

drop policy if exists "select_own_goal" on public.diet_user_settings;
drop policy if exists "insert_own_goal" on public.diet_user_settings;
drop policy if exists "update_own_goal" on public.diet_user_settings;

create policy "diet_user_settings_select_own"
on public.diet_user_settings
for select
using (auth.uid() = user_id);

create policy "diet_user_settings_insert_own"
on public.diet_user_settings
for insert
with check (auth.uid() = user_id);

create policy "diet_user_settings_update_own"
on public.diet_user_settings
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- ---------- API quota storage ----------
create table if not exists public.api_usage_buckets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bucket text not null,
  used_count integer not null default 0,
  window_start timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint api_usage_buckets_used_count_non_negative check (used_count >= 0),
  constraint api_usage_buckets_unique_window unique (user_id, bucket, window_start)
);

create index if not exists idx_api_usage_buckets_user_bucket_window
  on public.api_usage_buckets (user_id, bucket, window_start desc);

revoke all on table public.api_usage_buckets from anon;
revoke all on table public.api_usage_buckets from public;

alter table public.api_usage_buckets enable row level security;

drop policy if exists "api_usage_buckets_no_direct_access" on public.api_usage_buckets;
create policy "api_usage_buckets_no_direct_access"
on public.api_usage_buckets
for all
using (false)
with check (false);

create or replace function public.tg_set_api_usage_buckets_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_api_usage_buckets_updated_at on public.api_usage_buckets;
create trigger trg_api_usage_buckets_updated_at
before update on public.api_usage_buckets
for each row
execute function public.tg_set_api_usage_buckets_updated_at();

-- ---------- Quota RPC: atomic consume ----------
create or replace function public.check_and_consume_api_quota(
  p_bucket text,
  p_limit integer,
  p_window_seconds integer,
  p_consume integer default 1
)
returns table(allowed boolean, remaining integer, window_start timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_now timestamptz := now();
  v_window_start timestamptz;
  v_used integer;
begin
  if v_user_id is null then
    return query select false, 0, null::timestamptz;
    return;
  end if;
  if p_bucket is null or length(trim(p_bucket)) = 0 then
    raise exception 'bucket_required';
  end if;
  if p_limit is null or p_limit <= 0 then
    raise exception 'limit_invalid';
  end if;
  if p_window_seconds is null or p_window_seconds <= 0 then
    raise exception 'window_seconds_invalid';
  end if;
  if p_consume is null or p_consume <= 0 then
    raise exception 'consume_invalid';
  end if;

  v_window_start := to_timestamp(floor(extract(epoch from v_now) / p_window_seconds) * p_window_seconds);

  insert into public.api_usage_buckets (user_id, bucket, used_count, window_start)
  values (v_user_id, p_bucket, 0, v_window_start)
  on conflict (user_id, bucket, window_start) do nothing;

  select used_count into v_used
  from public.api_usage_buckets
  where user_id = v_user_id and bucket = p_bucket and window_start = v_window_start
  for update;

  if coalesce(v_used, 0) + p_consume > p_limit then
    return query select false, greatest(p_limit - coalesce(v_used, 0), 0), v_window_start;
    return;
  end if;

  update public.api_usage_buckets
  set used_count = coalesce(v_used, 0) + p_consume
  where user_id = v_user_id and bucket = p_bucket and window_start = v_window_start;

  return query select true, greatest(p_limit - (coalesce(v_used, 0) + p_consume), 0), v_window_start;
end;
$$;

revoke all on function public.check_and_consume_api_quota(text, integer, integer, integer) from public;
grant execute on function public.check_and_consume_api_quota(text, integer, integer, integer) to authenticated;

commit;
